name: Notify Updates To Github Pages Repo

on:
  push:
    branches:
      - main
  
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_PAT_TAGMARK }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.actor }}/${{ vars.GH_PAGES_REPO }}/dispatches \
            -d '{"event_type":"tagmark-ui-main-update"}'